# Generated by Django 3.1.2 on 2020-10-17 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/', validators=[django.core.validators.validate_image_file_extension])),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256, null=True, unique=True)),
                ('followers', models.ManyToManyField(blank=True, default=None, related_name='profile_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
